### ISSUE TITLE
error when run demo_video/demo_long_video.py

### ISSUE THREAD

**Issue by BHM-Bob** [Seung-Hun-Lee/CAVIS#2]
I appreciate your work. I'm not familiar with video segmentation and simply want to use your work as a valuable tool. However, I encountered errors when following the installation instructions and running demo_video/demo_long_video.py:

1. I received a ModuleNotFoundError stating `No module named 'dvis'`. I resolved this by changing `dvis` to `cavis` in the line: `from dvis import add_minvis_config, add_dvis_config`. I assume it works but may cause follow error.

2. I encountered a KeyError with the message `Non-existent config key: MODEL.MASK_FORMER.CONTEXT_FILTER_SIZE`. I am unsure how to address this issue.

Any assistance would be appreciated.

**Comment by Seo-jiwan** [comment]
We haven't been able to check the demo_long_video.py file. 

Could you try using `from cavis import add_minvis_config, add_cavis_config, add_dvis_config` instead of `from dvis import add_minvis_config, add_dvis_config` in demo_long_video.py? 

I hope this works well. 
Thank you for the correction.

**Comment by BHM-Bob** [comment]
Thanks for your replay. For the sceond issue, I think I may just use the wrong config haha.
